imports:
    - { resource: "services/form.yml" }

services:
    _defaults:
        public: true

    coreshop.configuration.service: '@CoreShop\Component\Configuration\Service\ConfigurationService'
    CoreShop\Component\Configuration\Service\ConfigurationServiceInterface: '@CoreShop\Component\Configuration\Service\ConfigurationService'
    CoreShop\Component\Configuration\Service\ConfigurationService:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@coreshop.repository.configuration'
            - '@coreshop.factory.configuration'

    CoreShop\Component\Configuration\Serialization\ObjectHandler:
        tags:
          - { name: jms_serializer.handler, type: object, direction: serialization, format: json, method: serializeRelation }
